### ISSUE TITLE
Update training to latest helm charts

### ISSUE THREAD

**Issue by danielpcox** [DecipherNow/workshops#6]
Because the Grey Matter helm install was misbehaving for the very latest helm charts because of a TLS issue, we specified an older version. Fix this and re-test whole training flow to upgrade.

**Comment by chrisbsmith** [comment]
@danielpcox can you go into more detail on the issue you experienced?

**Comment by danielpcox** [comment]
Yes, @kaitmore reported it, so lemme extract her comments...

```
{"level":"fatal","service":"gm-control-api","tlsutil.NewTLSConfig":"error adding CA trust to pool: <nil>","time":"2019-11-18T22:08:47Z","message":"unable to startServer with TLS"}
```

> Kait: I'm going through the installation guide to test the aws creds, and gm-control-api is crashing with the error I posted above.
> 
> Ok I see. `wget https://raw.githubusercontent.com/DecipherNow/helm-charts/release-2.0/greymatter-secrets.yaml` needs to pull from release-2.1
> Or, I need to back-merge that tls PR
> What do you want to do?
> 
> Daniel: Oh, so my wget is not pulling from the default branch anymore?
> The default branch has changed?
> 
> Kait Moreno: Looks like it...
> I am very confused how the helm charts are being versioned

So it looks like the training material was pointing to the default branch, which changed. But `greymatter.yaml` in the one I was actually using (2.0) still had the TLS switch set even though the feature was only implemented in 2.1?

We may be able to fix this just by having the training materials pointed at the current latest version as of right now, and be more careful in the future about keeping the helm override yamls tracking with their own branch.

I'd also prefer that we weren't always changing the default branch of the repo and expecting that to mean something.

**Comment by kaitmore** [comment]
Just looked at this again and I think it was the opposite actually: we were pulling `greymatter.yaml` from the 2.0 branch, but the helm charts that we were pulling from nexus were from the latest default branch (release-2.1). 

The reason that we were seeing tls errors even though the tls switch wasn't present in greymatter.yaml is because `control` and `control-api` had `control_api_tls: true` set in their respective `values.yaml` files, but had dummy cert files.

**Comment by chrisbsmith** [comment]
@danielpcox we are changing the default branch to the current release being worked.  This is still a new git process for everyone, so we can certainly discuss it.

From what I'm reading, it doesn't seem like this is actually a technical issue as much as it's a documentation/versioning error.

Concurrence @kaitmore @danielpcox ?

**Comment by kaitmore** [comment]
Agreed. We just need a more reliable way to tie the greymatter custom yamls to the helm charts in Nexus so that we don't have to update the workshops every time the default branch changes.

**Comment by danielpcox** [comment]
Perhaps we can just have `master` always track the latest release branch.

**Comment by hiromis** [comment]
I just run through with the following workshops with the head of branch `release-2.1` of https://github.com/DecipherNow/helm-charts (commit b6cb283e8bd1d812bd2d75f5ec293b8cdce4b554 (HEAD -> release-2.1)):

- Grey Matter Installation
- Grey Matter Service Deployment

Everything went perfectly with just one minor hiccup. This command `export PORT=$( sudo minikube service list | grep voyager-edge | grep -oP ':\K(\d+)' )` chose the port `30001` instead of `30000` which resulted in the next step to hang indefinitely:

```
ubuntu@ip-172-31-39-88:~$ greymatter list cluster
[info] 2019/12/03 16:22:58 Preferring --api.key for authentication
```

I manually updated `GREYMATTER_API_HOST` environment to point to port 30000 and everything went smoothly with no issues.

**Comment by danielpcox** [comment]
I think from Hiromi's run that we can 
a) safely change `--version 2.0.4` to whatever the latest version is, and
b) update the training material so it recommends port 30000.

**Comment by danielpcox** [comment]
Fixed in that^ PR
